BOX_IMAGE = "bento/ubuntu-22.04"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", ip: "192.168.56.#{21+i}"
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "3072"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end

      subconfig.vm.provision "shell", inline: <<-SHELL
        for j in $(seq 1 #{NODE_COUNT}); do
          if [ $j -ne #{i} ]; then
            echo -e "192.168.56.$((21+j)) node$j" | sudo tee -a /etc/hosts
          fi
        done
      SHELL
    end
  end
end
